const books = [
    {
        id: 1,
        title: 'The Alchemist',
        author: 'Paulo Coelho',
        tags: ['fantasy', 'fiction'],
        stock: 10,
        rating: 4.75,
    },
    {
        id: 2,
        title: 'To Kill a Mockingbird',
        author: 'Harper Lee',
        tags: ['fiction', 'drama'],
        stock: 15,
        rating: 4.2,
    },
    {
        id: 3,
        title: 'The Great Gatsby',
        author: 'F. Scott Fitzgerald',
        tags: ['fiction', 'classics'],
        stock: 20,
        rating: 4.5,
    },
    {
        id: 4,
        title: '1984',
        author: 'George Orwell',
        tags: ['fiction', 'dystopian'],
        stock: 12,
        rating: 4.1,
    },
    {
        id: 5,
        title: 'Brave New World',
        author: 'Aldous Huxley',
        tags: ['science fiction', 'dystopian'],
        stock: 18,
        rating: 4.8,
    },
    {
        id: 6,
        title: 'The Catcher in the Rye',
        author: 'J.D. Salinger',
        tags: ['fiction', 'coming-of-age'],
        stock: 30,
        rating: 4.0,
    },
    {
        id: 7,
        title: 'Lord of the Flies',
        author: 'William Golding',
        tags: ['fiction', 'classics'],
        stock: 25,
        rating: 4.3,
    },
    {
        id: 8,
        title: 'Animal Farm',
        author: 'George Orwell',
        tags: ['fiction', 'satire'],
        stock: 17,
        rating: 4.6,
    },
    {
        id: 9,
        title: 'The Hobbit',
        author: 'J.R.R. Tolkien',
        tags: ['fantasy', 'adventure'],
        stock: 22,
        rating: 4.9,
    },
    {
        id: 10,
        title: 'Harry Potter and the Sorcerer\'s Stone',
        author: 'J.K. Rowling',
        tags: ['fantasy', 'magic'],
        stock: 28,
        rating: 4.7,
    },
    {
        id: 11,
        title: 'The Da Vinci Code',
        author: 'Dan Brown',
        tags: ['mystery', 'thriller'],
        stock: 16,
        rating: 3.9,
    },
    {
        id: 12,
        title: 'The Hunger Games',
        author: 'Suzanne Collins',
        tags: ['science fiction', 'dystopian'],
        stock: 20,
        rating: 4.2,
    },
    {
        id: 13,
        title: 'Gone Girl',
        author: 'Gillian Flynn',
        tags: ['mystery', 'thriller'],
        stock: 19,
        rating: 4.4,
    },
    {
        id: 14,
        title: 'The Fault in Our Stars',
        author: 'John Green',
        tags: ['fiction', 'romance'],
        stock: 15,
        rating: 4.6,
    },
    {
        id: 15,
        title: 'The Girl with the Dragon Tattoo',
        author: 'Stieg Larsson',
        tags: ['mystery', 'thriller'],
        stock: 23,
        rating: 4.3,
    },
    {
        id: 16,
        title: 'The Road',
        author: 'Cormac McCarthy',
        tags: ['fiction', 'post-apocalyptic'],
        stock: 10,
        rating: 4.1,
    },
    {
        id: 17,
        title: 'The Shining',
        author: 'Stephen King',
        tags: ['horror'],
        stock: 27,
        rating: 4.9,
    },
    {
        id: 18,
        title: 'The Kite Runner',
        author: 'Khaled Hosseini',
        tags: ['fiction', 'drama'],
        stock: 14,
        rating: 4.2,
    },
    {
        id: 19,
        title: 'The Help',
        author: 'Kathryn Stockett',
        tags: ['fiction', 'historical'],
        stock: 18,
        rating: 4.5,
    },
    {
        id: 20,
        title: 'The Handmaid\'s Tale',
        author: 'Margaret Atwood',
        tags: ['dystopian', 'feminism'],
        stock: 21,
        rating: 4.8,
    },
    {
        id: 21,
        title: 'The Lord of the Rings',
        author: 'J.R.R. Tolkien',
        tags: ['fantasy', 'adventure'],
        stock: 30,
        rating: 4.7,
    },
    {
        id: 22,
        title: 'The Chronicles of Narnia',
        author: 'C.S. Lewis',
        tags: ['fantasy'],
        stock: 25,
        rating: 4.4,
    },
    {
        id: 23,
        title: 'Divergent',
        author: 'Veronica Roth',
        tags: ['science fiction', 'dystopian'],
        stock: 16,
        rating: 4.3,
    },
    {
        id: 24,
        title: 'The Martian',
        author: 'Andy Weir',
        tags: ['science fiction'],
        stock: 19,
        rating: 4.6,
    },
    {
        id: 25,
        title: 'A Game of Thrones',
        author: 'George R.R. Martin',
        tags: ['fantasy', 'epic'],
        stock: 24,
        rating: 4.9,
    },
    {
        id: 26,
        title: 'The Color Purple',
        author: 'Alice Walker',
        tags: ['fiction', 'drama'],
        stock: 17,
        rating: 4.5,
    },
    {
        id: 27,
        title: 'The Road Less Traveled',
        author: 'M. Scott Peck',
        tags: ['self-help'],
        stock: 12,
        rating: 4.2,
    },
    {
        id: 28,
        title: 'The Girl on the Train',
        author: 'Paula Hawkins',
        tags: ['mystery', 'thriller'],
        stock: 22,
        rating: 4.4,
    },
    {
        id: 29,
        title: 'The Secret Garden',
        author: 'Frances Hodgson Burnett',
        tags: ['classics', 'children'],
        stock: 20,
        rating: 4.0,
    },
];

export default books;