const tags = [
    { id: 0, name: 'all books'},
    { id: 1, name: 'fantasy' },
    { id: 2, name: 'fiction' },
    { id: 3, name: 'drama' },
    { id: 4, name: 'classics' },
    { id: 5, name: 'dystopian' },
    { id: 6, name: 'science fiction' },
    { id: 7, name: 'coming-of-age' },
    { id: 8, name: 'satire' },
    { id: 9, name: 'adventure' },
    { id: 10, name: 'magic' },
    { id: 11, name: 'mystery' },
    { id: 12, name: 'thriller' },
    { id: 13, name: 'romance' },
    { id: 14, name: 'post-apocalyptic' },
    { id: 15, name: 'horror' },
    { id: 16, name: 'historical' },
    { id: 17, name: 'feminism' },
    { id: 18, name: 'epic' },
    { id: 19, name: 'self-help' },
    { id: 20, name: 'children' },
];

export default tags;
